#!/usr/bin/env python3
"""
Security Audit — Second Brain
Scans for PII, credentials, and security issues.

Usage: python security-audit.py
"""

import os
import re
from pathlib import Path

VAULT_ROOT = Path(__file__).parent.parent.parent

# Patterns to scan for
PATTERNS = {
    "email": re.compile(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'),
    "phone": re.compile(r'(\+66|0)\d{8,9}'),
    "api_key": re.compile(r'(api[_-]?key|apikey|secret|password|token|credential)\s*[=:]\s*["\'][^"\']{8,}["\']', re.IGNORECASE),
    "aws_key": re.compile(r'AKIA[0-9A-Z]{16}'),
    "github_token": re.compile(r'ghp_[a-zA-Z0-9]{36}'),
    "private_key": re.compile(r'-----BEGIN (RSA |EC )?PRIVATE KEY-----'),
    "env_var": re.compile(r'(GOOGLE_API_KEY|GROQ_API_KEY|OPENROUTER_API_KEY|ANTHROPIC_API_KEY)\s*[=:]\s*["\']?[^\s"\']+'),
    "hardcoded_path": re.compile(r'C:\\Users\\[a-zA-Z]+\\'),
    "ip_address": re.compile(r'\b(?:\d{1,3}\.){3}\d{1,3}\b'),
}

# Directories to skip
SKIP_DIRS = {'.git', 'node_modules', '__pycache__', '.smart-env', 'Backups'}


def scan_file(filepath):
    """Scan a single file for security issues."""
    issues = []
    try:
        content = filepath.read_text(encoding='utf-8', errors='ignore')
        for line_num, line in enumerate(content.split('\n'), 1):
            for pattern_name, pattern in PATTERNS.items():
                matches = pattern.findall(line)
                if matches:
                    # Skip obvious false positives
                    if pattern_name == "email" and any(skip in line.lower() for skip in ['example', 'test', 'user@', 'email@example', 'noreply']):
                        continue
                    if pattern_name == "hardcoded_path" and 'C:\\Users\\menum\\Documents\\ObsidianVault' in line:
                        continue
                    if pattern_name == "env_var" and 'os.getenv' in line:
                        continue
                    issues.append((pattern_name, line_num, line.strip()[:100]))
    except Exception:
        pass
    return issues


def scan_vault():
    """Scan entire vault for security issues."""
    all_issues = []
    files_scanned = 0

    for root, dirs, files in os.walk(VAULT_ROOT):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for f in files:
            if not f.endswith(('.md', '.json', '.py', '.sh', '.ps1', '.yml', '.yaml')):
                continue
            filepath = Path(root) / f
            issues = scan_file(filepath)
            if issues:
                for pattern_name, line_num, line_content in issues:
                    all_issues.append({
                        'file': str(filepath.relative_to(VAULT_ROOT)),
                        'line': line_num,
                        'type': pattern_name,
                        'content': line_content
                    })
            files_scanned += 1

    return all_issues, files_scanned


def generate_report(issues, files_scanned):
    """Generate security audit report."""
    report = f"""---
type: security-audit
generated: '2026-06-04'
---

# Security Audit Report

Generated: 2026-06-04

## Summary

| Metric | Value |
|--------|-------|
| Files scanned | {files_scanned} |
| Issues found | {len(issues)} |

## Issues by Type

"""
    # Group by type
    by_type = {}
    for issue in issues:
        t = issue['type']
        if t not in by_type:
            by_type[t] = []
        by_type[t].append(issue)

    for issue_type, items in sorted(by_type.items()):
        report += f"### {issue_type.upper()} ({len(items)} found)\n\n"
        for item in items[:5]:
            report += f"- `{item['file']}` line {item['line']}: `{item['content'][:80]}`\n"
        if len(items) > 5:
            report += f"- *... and {len(items) - 5} more*\n"
        report += "\n"

    # Risk assessment
    report += "## Risk Assessment\n\n"
    critical = by_type.get('private_key', []) + by_type.get('aws_key', []) + by_type.get('github_token', [])
    high = by_type.get('api_key', []) + by_type.get('env_var', [])
    medium = by_type.get('hardcoded_path', [])
    low = by_type.get('email', []) + by_type.get('phone', []) + by_type.get('ip_address', [])

    report += f"- **Critical**: {len(critical)} (private keys, AWS keys, GitHub tokens)\n"
    report += f"- **High**: {len(high)} (API keys, env vars)\n"
    report += f"- **Medium**: {len(medium)} (hardcoded paths)\n"
    report += f"- **Low**: {len(low)} (emails, phones, IPs)\n\n"

    if not critical and not high:
        report += "**Overall**: No critical or high-severity issues found.\n"
    else:
        report += "**Action Required**: Review critical and high severity issues.\n"

    report += "\n---\n*Report generated by security-audit.py*\n"
    return report


if __name__ == "__main__":
    print("Running security audit...")
    issues, files_scanned = scan_vault()
    print(f"Scanned {files_scanned} files, found {len(issues)} issues")

    report = generate_report(issues, files_scanned)

    report_path = VAULT_ROOT / "Meta" / "health" / "security-audit-report.md"
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(report, encoding='utf-8')
    print(f"Report saved to: {report_path}")

    # Print summary
    print(f"\n{'='*60}")
    by_type = {}
    for issue in issues:
        t = issue['type']
        by_type[t] = by_type.get(t, 0) + 1
    for t, count in sorted(by_type.items(), key=lambda x: -x[1]):
        print(f"  {t}: {count}")
    print(f"{'='*60}")
